[package]
name = "arrow_nif"
version = "0.1.0"
authors = ["Benedikt Reinartz <filmor@gmail.com>"]
edition = "2018"

[lib]
name = "arrow_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.20"
lazy_static = "1.0"
arrow = "0.13"
